// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/app-list/CardPageWithBigThumbnail.html":'\x3cdiv\x3e\r\n\t\x3cdiv class\x3d"card-page-content" data-dojo-attach-point\x3d"cardPageContent"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/html dojo/_base/array dojo/_base/lang dojo/on dojo/dom ./AppOperMenu dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./CardPageWithBigThumbnail.html jimu/utils dojox/form/Uploader dojo/NodeList-dom".split(" "),function(p,b,k,l,m,q,r,t,u,v,w,e){return p([t,u,v],{baseClass:"card-page",templateString:w,loading:null,folderUrl:null,appListWidget:null,_eventHandles:null,_appOperMenus:null,postMixInProperties:function(){this.inherited(arguments);
this.nls=this.appListWidget.nls;this.loading=this.appListWidget.loading;this.folderUrl=this.appListWidget.folderUrl},constructor:function(){this._eventHandles=[];this._appOperMenus=[]},startup:function(){this.inherited(arguments);b.setSelectable(this.domNode,!1)},refresh:function(a){this.createItemList(a)},cleanItemList:function(){b.empty(this.cardPageContent);k.forEach(this._appOperMenus,function(a){a.destroy()});this._appOperMenus=[];k.forEach(this._eventHandles,function(a){a.remove()});this._eventHandles=
[]},createItemList:function(a){this.cleanItemList();0<a.length?k.forEach(a,function(a){this.createItemCard(a)},this):this.appListWidget._addEmptyDescription(this.cardPageContent,"card-page")},createItemCard:function(a){var f=a.isTemplate?this.nls.preview:this.nls.launch,d=b.create("div",{"class":"item-card jimu-float-leading"},this.cardPageContent),c=b.create("a",{"class":"thumbnail-part",style:"background-image: url("+a.thumbnail+"?date\x3d"+this.appListWidget.getRefreshImageFlag()+")",href:a.appUrl,
target:"_blank",title:f},d);b.create("div",{"class":"item-type-div "+("HTML"===a.appType?"item-type-2d":"item-type-3d")},c);c=b.create("div",{"class":"appInfo-part"},d);b.create("div",{"class":"item-name-div",innerHTML:e.sanitizeHTML(a.name),title:a.name},c);var n=b.create("div",{"class":"item-info-div"},c);b.create("div",{"class":"app-time-div jimu-float-leading",innerHTML:e.sanitizeHTML(this.appListWidget._getLocaleDateTime(a.lastUpdated))},n);b.create("div",{"class":"app-creator-div jimu-float-trailing",
innerHTML:e.sanitizeHTML(a.creator)},n);c=b.create("div",{"class":"desc-wrap jimu-clamp-wrap"},c);b.create("div",{"class":"item-des-div clamp "+(a.description?"":"place-holder-class"),innerHTML:a.description?e.sanitizeHTML(a.description):this.nls.defaultDesc,title:a.description},c);d=b.create("div",{"class":"item-operation-part"},d);b.create("div",{innerHTML:'\x3ca href\x3d"'+e.sanitizeHTML(a.appUrl)+'" target\x3d"_blank"\x3e\x3c/a\x3e',"class":"item-operation launch-operation jimu-float-leading",
title:f},d);a.isTemplate||b.create("div",{innerHTML:'\x3ca href\x3d"'+e.sanitizeHTML(a.downloadUrl)+'" target\x3d"downloadTargetFrame"\x3e\x3c/a\x3e',"class":"item-operation download-operation jimu-float-leading",title:this.nls.download},d);var f=b.create("div",{"class":"item-operation edit-operation jimu-float-leading "+(a.isPredefined?"disable":""),title:a.isTemplate?this.nls.configTemplate:this.nls.configApp},d),g=b.create("div",{"class":"item-operation more-operation jimu-float-trailing "+(a.isPredefined?
"disable":"")},d),h=(new r({app:a,posNode:g,appListWidget:this.appListWidget,nls:this.nls,isTemplate:a.isTemplate,appContentNode:this.cardPageContent,height:a.isTemplate?a.isPredefined?45:162:122,offset:{top:44,left:-10,right:-10}})).placeAt(g);this._appOperMenus.push(h);c=m(g,"click",l.hitch(this,function(c){h.isShow?(h.hide(),b.removeClass(g,"item-more-selected")):(k.forEach(this._appOperMenus,function(a){a.hide();b.removeClass(a.posNode,"item-more-selected")}),h.show(),b.addClass(g,"item-more-selected"));
c.itemId=a.id}));this._eventHandles.push(c);c=m(f,"click",l.hitch(this,function(){this.appListWidget.pluginManager.getPluginByName("startup").switchToAppConfig(a)}));this._eventHandles.push(c);a.isTemplate&&(f=b.create("div",{"class":"item-operation create-app-from-item-operation jimu-float-leading",title:this.nls.createApp},d),c=m(f,"click",l.hitch(this,function(){h._onCreateAppFromTempalteClick()})),this._eventHandles.push(c));c=m(q.byId("content-box"),"click",l.hitch(this,function(c){c.itemId!==
a.id&&(h.hide(),b.removeClass(g,"item-more-selected"))}));this._eventHandles.push(c)}})});